### ISSUE TITLE
help

### ISSUE THREAD

**Issue by theClueless** [maximveksler/awesome-serialization#3]
Hi,

Not sure if you can help but I'm trying to find a format that will help solve a very particular problem:
- Text first solution.
- Ability to specify complex objects in a single text line (properties, key\value, lists, complex objects)
- Object metadata structure should be separate from the data.

For example:
Metadata: Prop1:int|Prop2:string|PropList:int[,]
Data: 20|Something|10,20,30

that would mean:
Prop1 = 20
Prop2 = "Something"
PropList = [10,20,30]

Is there any existing serialization format resembling this?

**Comment by maximveksler** [comment]
@theClueless how about JSONL? https://jsonlines.org/examples/

**Comment by maximveksler** [comment]
I would hold off from specifying the metadata separately. as that would complicate the format. If indeed that's a requirements perhaps [json-ld](https://json-ld.org/) could work for the use case?

**Comment by maximveksler** [comment]
Let's close this issue as stale. Happy to re-open and continue the discussion.
